name: easyocr
services:
  proxy:
    image: "tinyproxy"
    networks:
      - external
      - internal
    volumes:
      - ./tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf
  http:
    image: "caddy"
    restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      - app
    ports:
      - 7863:7860
    volumes:
      - ./caddy.easyocr.Caddyfile:/etc/caddy/Caddyfile
  app:
    image: "easyocr:v1"
    restart: unless-stopped
    networks:
      - internal
    environment:
      - http_proxy=http://proxy:8118
      - https_proxy=http://proxy:8118
      - no_proxy=localhost,127.0.0.1
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    volumes:
      - ./models/easyocr:/root/.EasyOCR/model:z
      - ./easyocr/app.py:/app/app.py:z
      - ./data:/app/outputs:z
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
networks:
  external:
  internal:
    internal: true
