name: comfyui
services:
  proxy:
    image: "tinyproxy"
    networks:
      - external
      - internal
    volumes:
      - ./tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf
  http:
#    image: "nginx"
    image: "caddy"
    networks:
      - external
      - internal
    depends_on:
      - app
    ports:
      - 7861:7860
    volumes:
#      - ./nginx.sdui.conf:/etc/nginx/conf.d/nginx.sdui.conf
      - ./caddy.sdui.Caddyfile:/etc/caddy/Caddyfile
  app:
    image: "comfyui:v1"
    networks:
      - internal
    environment:
      - http_proxy=http://proxy:8118
      - https_proxy=http://proxy:8118
      - no_proxy=localhost,127.0.0.1
    volumes:
      - ./data:/data:z
      - ./models:/home/user/app/models:z
    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
networks:
  external:
  internal:
    internal: true
