name: qwen
services:
  proxy:
    image: "tinyproxy"
    networks:
      - external
      - internal
    volumes:
      - ./tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf
  http:
    image: "caddy"
    networks:
      - external
      - internal
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./caddy.qwen.Caddyfile:/etc/caddy/Caddyfile
  app:
    image: "qwenllm/qwen:cu117"
    command:
      - "python"
      - "web_demo.py"
      - "--server-port"
      - "80"
      - "--server-name"
      - "0.0.0.0"
      - "-c"
      - "/data/shared/Qwen/Qwen-Chat/"
    networks:
      - internal
    environment:
      - http_proxy=http://proxy:8118
      - https_proxy=http://proxy:8118
      - no_proxy=localhost,127.0.0.1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    volumes:
      - ./models/qwen:/data/shared/Qwen/Qwen-Chat:z

networks:
  external:
  internal:
    internal: true
